spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/order-advance
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true

#        use_sql_comments: true
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:sql/data-h2.sql # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정
